# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9bbd173a2417784d83c07b7e0e76a6ae77a461f55b9f1625d836f208b12733995df836a801914937a059db5d75561fca076c29da095ff4a3a1c639adb523ba7

test:
  secret_key_base: f033d7cc285829fd8edc090e23c74a4adac17a4fbba85d0d64cfa00518701fa615fafc112b43b0fac610fb87605a3f4e21b8435b7ca4e17898ba0025f4f94c4d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
